name: clamav-malware-scanner
environment: "dev"
replicaCount: 1

gcp:
  project: my-project
  region: us-east4
  gar:
    project: my-project
    repo: application

storage:
  postgres:
    enabled: false

mirror:
  image:
    pullPolicy: IfNotPresent
    name: clamav-mirror
    tag: latest
  net:
    applicationPort: 8000
    servicePort: 8000
  readinessProbe:
    initialdelaySeconds: 180
    periodSeconds: 10
  resources:
    update:
      mem:
        min: "25Mi"
        max: "50Mi"
    cron:
      mem:
        min: "25Mi"
        max: "50Mi"

clamav:
  image:
    pullPolicy: IfNotPresent
    name: clamav/clamav
    tag: unstable_base
  net:
    applicationPort: 3310
    servicePort: 3310
  readinessProbe:
    initialdelaySeconds: 30
    periodSeconds: 10
  startupProbe:
    failureThreshold: 60
    periodSeconds: 10
  resources:
    mem:
      min: "1400Mi"
      max: "2000Mi"


worker:
  image:
    pullPolicy: IfNotPresent
    name: clamav-worker
    tag: latest
  net:
    applicationPort: 8080
    servicePort: 8080
  readinessProbe:
    initialdelaySeconds: 10
    periodSeconds: 10
    failureThreshold: 6
  env:
    UNSCANNED_BUCKET: my-unscanned-bucket
    CLEAN_BUCKET: my-scanned-bucket
    QUARANTINED_BUCKET: my-quarantined-bucket
    UPLOAD_TOPIC: projects/my-project/topics/my-topic
    CLAMD_HOST: clamd-service
    CLAMD_PORT: '3310'
  resources:
    mem:
      min: "150Mi"
      max: "300Mi"
