apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav-worker
  labels:
    app: clamav-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: clamav-worker
  template:
    metadata:
      labels:
        app: clamav-worker
    spec:
      containers:
        - name: clamav-worker
          image: {{ .Values.gcp.region }}-docker.pkg.dev/{{ .Values.gcp.gar.project }}/{{ .Values.gcp.gar.repo }}/{{ .Values.worker.image.name }}:{{ .Values.worker.image.tag }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            {{- include "env.tpl" .Values.worker | indent 12}}
          readinessProbe:
            failureThreshold: {{ .Values.worker.readinessProbe.failureThreshold }}
            httpGet:
              path: /
              port: {{ .Values.worker.net.applicationPort }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.worker.readinessProbe.initialDelaySeconds | default 30 }}
            periodSeconds: {{ .Values.worker.readinessProbe.periodSeconds | default 10 }}
          resources:
            requests:
              memory: {{ .Values.worker.resources.mem.min }}
            limits:
              memory: {{ .Values.worker.resources.mem.max }}
