apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav-mirror
  labels:
    app: clamav-mirror
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: clamav-mirror
  template:
    metadata:
      labels:
        app: clamav-mirror
    spec:
      containers:
        - name: cvdupdate-server
          image: cvdupdate:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              cvdupdate config set -d /opt/db
              cvdupdate serve
          volumeMounts:
            - name: data
              mountPath: /opt/db
        - name: cvdupdate-cron
          image: cvdupdate:latest
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "#!/bin/sh" >> /etc/periodic/hourly/cvdupdate
              echo "cvdupdate update" >> /etc/periodic/hourly/cvdupdate
              chmod +x /etc/periodic/hourly/cvdupdate
              cvdupdate config set -d /opt/db
              cvdupdate update
              crond -f -l 8
          volumeMounts:
            - name: data
              mountPath: /opt/db
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: cvdupdate-service
spec:
  selector:
    app: clamav-mirror
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  sessionAffinity: None
  type: NodePort
