apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-worker
  labels:
    app: node-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: node-worker
  template:
    metadata:
      labels:
        app: node-worker
    spec:
      containers:
        - name: node-worker
          image: clamav-node-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: UNSCANNED_BUCKET
              value: my-unscanned-bucket
            - name: CLEAN_BUCKET
              value: my-scanned-bucket
            - name: QUARANTINED_BUCKET
              value: my-quarantined-bucket
            - name: UPLOAD_TOPIC
              value: projects/my-project/topics/my-topic
            - name: CLAMD_HOST
              value: 127.0.0.1
            - name: CLAMD_PORT
              value: '3310'
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
