apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-worker
  labels:
    app: node-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: node-worker
  template:
    metadata:
      labels:
        app: node-worker
    spec:
      containers:
        - name: node-worker
          image: clamav-node-worker:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: UNSCANNED_BUCKET
              value: ocm-dev-sandbox-document-management-unscanned
            - name: CLEAN_BUCKET
              value: ocm-dev-sandbox-document-management-scanned
            - name: QUARANTINED_BUCKET
              value: ocm-dev-sandbox-document-management-quarantine
            - name: UPLOAD_TOPIC
              value: projects/ny-ocm-dev-sandbox/topics/unscanned-upload 
            - name: CLAMD_HOST
              value: clamd-service
            - name: CLAMD_PORT
              value: '3310'
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 1
