# Example file for specifying the configuration using environment variables.
#
# use with the --env-vars-file argument to gcloud run deploy.
#
# The CONFIG_JSON variable contains the JSON configuration which will
# override any deployed config.json file. Literal Block Scaler style (|)
# is used to preserve quotes and newlines without needing escaping.
#
CONFIG_JSON: |
  {
    "buckets": [
      {
        "unscanned": "unscanned-bucket-name",
        "clean": "clean-bucket-name",
        "quarantined": "quarantined-bucket-name"
      }
    ],
    "ClamCvdMirrorBucket": "cvd-mirror-bucket-name"
  }
