version: '3'

services:
  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: clamav
    ports:
      - 3310:3310
    volumes:
      - clam:/var/lib/clamav

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

volumes:
  clam:
