apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-worker
  labels:
    app: node-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: node-worker
  template:
    metadata:
      labels:
        app: node-worker
    spec:
      containers:
        - name: node-worker
          image: {{ .Values.gcp.region }}-docker.pkg.dev/{{ .Values.gcp.project }}/{{ .Values.gcp.gar.repo }}/{{ .Values.worker.image.name }}:{{ .Values.worker.image.tag }}
          imagePullPolicy: {{ .Values.worker.image.pullPolicy }}
          env:
            {{- include "env.tpl" .Values.worker | indent 12}}
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: {{ .Values.worker.net.applicationPort }}
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 30
            timeoutSeconds: 1
