name: clamav-malware-scanner
environment: "dev"
replicaCount: 1

gcp:
  project: my-project
  region: us-east4
  gar:
    project: my-gar-project
    repo: application

storage:
  postgres:
    enabled: false

mirror:
  image:
    pullPolicy: IfNotPresent
    name: cvdupdate
    tag: latest
  net:
    applicationPort: 8000
    servicePort: 8000

clamd:
  image:
    pullPolicy: IfNotPresent
    name: clamav/clamav
    tag: unstable_base
  net:
    applicationPort: 3310
    servicePort: 3310


worker:
  image:
    pullPolicy: IfNotPresent
    name: node-worker
    tag: latest
  net:
    applicationPort: 8080
    servicePort: 8080
  env:
    UNSCANNED_BUCKET: my-bucket-unscanned
    CLEAN_BUCKET: my-bucket-scanned
    QUARANTINED_BUCKET: my-bucket-quarantined
    UPLOAD_TOPIC: projects/my-project/topics/my-topic
    CLAMD_HOST: 127.0.0.1
    CLAMD_PORT: 3310
