name: "ESLint"

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

jobs:
  analyze:
    name: "Eslint-analyze"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODEJS_VERSION }}
        check-latest: true
        always-auth: true

    # Install eslint
    - name: Install eslint
      working-directory: cloudrun-malware-scanner/
      run: npm install eslint eslint-config-google

    - name: Run eslint
      working-directory: cloudrun-malware-scanner/
      run: npm run eslint
